import { Metadata } from "next";
import "./globals.css";
import ConnectionLibraries from "@/hooks/ConnectionLibraries";

export const metadata: Metadata = {
  title: "Next Task",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConnectionLibraries>{children}</ConnectionLibraries>
      </body>
    </html>
  );
}
