import { Metadata } from "next"
import './globals.css'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ style: "normal", weight: "400" })

export const metadata: Metadata = {
  title: 'Next Task',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
